# Generated by Django 5.1 on 2024-08-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_defaultday_defaulttask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaulttask',
            name='completed',
        ),
        migrations.AlterField(
            model_name='defaultday',
            name='week_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
