# Generated by Django 5.1 on 2024-08-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_defaulttask_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='addef',
            field=models.BooleanField(default=False),
        ),
    ]
