# Generated by Django 5.1 on 2024-08-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_day_addef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='addef',
            new_name='defaultdone',
        ),
    ]
