# Generated by Django 6.0.3 on 2026-03-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_day_user_alter_defaultday_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulttask',
            name='is_everyday',
            field=models.BooleanField(default=False),
        ),
    ]
